### ISSUE TITLE
As a Lab-User I need a fast way to change from Celsius (C) to Fahrenheit (F).

### ISSUE THREAD

**Issue by jonny-pe** [Gamoel/ConversionCalculator#3]

**Comment by jonny-pe** [comment]
kurze Frage zu dem issue Hubert meinst du da change im bezug auf einheit wechseln im "frontend" oder calculate also umrechnen von Celsius auf Furz?

**Comment by Gamoel** [comment]
Hallo Dominik,
hier geht es darum einen API Request an das Backend zu schicken welches Celsius in Fahrenheit umrechnet.
